[package]
name = "elrage"
version = "1.0.0"
edition = "2021"

[dependencies]
age = {version = "0.10.0", features = ["ssh"]}
emacs_module = {path = "../emacs_module"}

[lib]
crate-type = ["rlib", "cdylib"]
